### PR TITLE
Couple fixes to allow build logs analyzer to also work in Unity Mac Editor

### PR DESCRIPTION
**Pull request by VoxelBoy**
As written in the title...

### CODE REVIEW

**Review by florin-cg — APPROVED** [review]
Thank you for the PR @VoxelBoy , I approved it. Feel free to merge it now.

**Comment by VoxelBoy** [comment]
@florin-cg I don't have write access therefore I cannot merge myself.

**Comment by florin-cg** [comment]
Ok, merging it. Thanks again for the PR!

**Comment by florin-cg** [comment]
Hi @VoxelBoy , 

We're planning to switch our project license from GPL to LGPL. Since you've contributed to this repository in the past, we wanted to reach out. If you have any concerns or objections, please let us know as soon as possible.

Thanks for your contribution!

**Comment by VoxelBoy** [comment]
@florin-cg No worries from my side.

**Pull request merged**
